
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-controller-manager:apiserver-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cloud-controller-manager
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:cloud-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - serviceaccounts/token
  - services
  - configmaps
  - endpoints
  - persistentvolumes
  - namespaces
  - secrets
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - node-controller
  - service-controller
  - route-controller
  resources:
  - serviceaccounts/token
  - secrets
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
    - get
    - list
    - watch
    - delete
    - patch
    - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
    - update
    - patch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
    - patch
    - update
- apiGroups:
  - ""
  resources:
  - events
  - endpoints
  verbs:
    - create
    - patch
    - update


