# Action by command-style comments (inspired by Kubernetes Prow)
name: "action by command-style comments"

# Event on a comment (in issue and PR)
on:
  issue_comment:
    types: [created]

jobs:
  execute:
    runs-on: ubuntu-18.04
    # Execute action according to commands
    steps:
      # Check author_association
      - name: Check author_association
        run: |
          echo event.comment.user.login is ${{ github.event.comment.user.login }}
          echo event.comment.author_association is ${{ github.event.comment.author_association }}
          echo Hello, this workflow is allowed to OWNER and MEMBER.     
      # Action according to command (by jpmcb/prow-github-actions)  
      # Execute when author_association of the comment is OWNER or MEMBER
      - name: Action according to command
        if: ${{ (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER') && startsWith(github.event.comment.body, '/') }}
        uses: jpmcb/prow-github-actions@v1.1.2
        with:
          prow-commands: '/assign 
            /unassign
            /approve 
            /retitle 
            /area 
            /kind 
            /priority 
            /remove 
            /lgtm 
            /close 
            /reopen 
            /lock 
            /milestone 
            /hold 
            /cc 
            /uncc'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
